#!/usr/bin/env bash
#
# Cloud KMS auto-unseal, run entirely locally and for free.
#
# The pieces, and what each one is for:
#
#   nahuelnucera/ministack:1.4.11   an AWS API emulator (MIT). Answers the KMS
#                                   wire protocol on port 4566 so a real AWS
#                                   SDK can talk to it. Stands in for AWS KMS.
#   amazon/aws-cli:2.36.16           the genuine AWS CLI, used to create the KMS
#                                   key and its alias. Not a mock client: it is
#                                   the same binary you would use against AWS,
#                                   pointed at a different endpoint.
#   openbao-plugin-kms-aws v0.1.0   the external KMS plugin that implements
#                                   seal "awskms". Baked into the image by this
#                                   directory's Dockerfile.
#   openbao/openbao:2.6.1           the default distribution. No custom base
#                                   image needed here, because the plugin is a
#                                   static Go binary. Contrast lesson 3.3.
#
# Usage: ./setup-awskms-unseal.sh   (needs docker, kubectl, helm 3.x, k3d, the lesson 1.2 cluster)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NS=openbao-kms
CLUSTER="${K3D_CLUSTER:-openbao-dev}"
IMAGE=openbao-awskms:lab
AWSCLI_IMAGE=amazon/aws-cli:2.36.16
KEY_ALIAS=alias/openbao-unseal

echo "==> 1. Build the image (stock OpenBao + the kms-aws plugin) and import it"
docker build -q -t "$IMAGE" "$HERE" >/dev/null
k3d image import "$IMAGE" -c "$CLUSTER" >/dev/null 2>&1
echo "   $IMAGE imported into k3d cluster $CLUSTER"

echo "==> 2. Read the plugin name and hash back out of the image"
# Reading them from the image rather than hardcoding is what keeps the
# sha256sum in the config identical to the binary actually present. If they
# disagree, OpenBao refuses to start, which is the behaviour you want but a
# miserable thing to debug by hand.
PLUGIN_BINARY="$(docker run --rm --entrypoint sh "$IMAGE" -c 'ls /openbao/plugins | grep ^openbao-plugin-kms-aws')"
PLUGIN_SHA256="$(docker run --rm --entrypoint sh "$IMAGE" -c 'cut -d" " -f1 /openbao/plugins/.sha256')"
echo "   plugin: $PLUGIN_BINARY"
echo "   sha256: $PLUGIN_SHA256"

echo "==> 3. Start MiniStack as the KMS endpoint"
kubectl create namespace "$NS" >/dev/null 2>&1 || true
kubectl -n "$NS" apply -f "$HERE/ministack.yaml" >/dev/null
kubectl -n "$NS" rollout status deploy/ministack --timeout=180s >/dev/null
echo "   ministack ready on :4566"

echo "==> 4. Create the KMS key and alias with the real AWS CLI"
# Note what is NOT happening here: no key material is generated by us. Unlike
# the PKCS#11 seal in lesson 3.3, a KMS seal asks the provider for a key and
# the provider makes it. This is the normal case; PKCS#11 was the exception.
run_aws() {
  kubectl -n "$NS" run awscli-$RANDOM --rm -i --restart=Never --quiet \
    --image="$AWSCLI_IMAGE" \
    --env=AWS_ACCESS_KEY_ID=test --env=AWS_SECRET_ACCESS_KEY=test \
    --env=AWS_DEFAULT_REGION=us-east-1 \
    --command -- aws --endpoint-url "http://ministack.${NS}.svc.cluster.local:4566" "$@"
}

if run_aws kms describe-key --key-id "$KEY_ALIAS" >/dev/null 2>&1; then
  echo "   $KEY_ALIAS already exists"
else
  KEY_ID="$(run_aws kms create-key --description "openbao auto-unseal" \
            | python3 -c "import sys,json;print(json.load(sys.stdin)['KeyMetadata']['KeyId'])")"
  run_aws kms create-alias --alias-name "$KEY_ALIAS" --target-key-id "$KEY_ID" >/dev/null
  echo "   created $KEY_ID and pointed $KEY_ALIAS at it"
fi

echo "==> 5. Install OpenBao with the awskms seal"
RENDERED="$(mktemp)"
trap 'rm -f "$RENDERED"' EXIT
sed -e "s|PLUGIN_BINARY|${PLUGIN_BINARY}|" \
    -e "s|PLUGIN_SHA256|${PLUGIN_SHA256}|" \
    "$HERE/values-awskms.yaml" > "$RENDERED"

helm repo add openbao https://openbao.github.io/openbao-helm >/dev/null 2>&1 || true
helm repo update >/dev/null 2>&1 || true
kubectl -n "$NS" delete secret awskms-creds >/dev/null 2>&1 || true
kubectl -n "$NS" create secret generic awskms-creds \
  --from-literal=access_key=test --from-literal=secret_key=test >/dev/null
helm install openbao openbao/openbao -n "$NS" --version 0.28.6 --values "$RENDERED" >/dev/null

for _ in $(seq 60); do
  phase="$(kubectl -n "$NS" get pod/openbao-0 -o jsonpath='{.status.phase}' 2>/dev/null || true)"
  [ "$phase" = "Running" ] && break
  sleep 3
done
[ "$phase" = "Running" ] || { echo "pod never reached Running (phase: ${phase:-absent})" >&2; exit 1; }

echo
kubectl -n "$NS" logs openbao-0 | grep -E 'Auto Seal|Cgo:' | sed 's/^/   /' || true

# Port-forward to the POD: the readiness probe is `bao status`, which fails
# until the instance is initialised, so the Service has no endpoints yet.
kubectl -n "$NS" port-forward pod/openbao-0 8200:8200 >/tmp/pf-awskms.log 2>&1 &
for _ in $(seq 30); do
  curl -s --max-time 2 -o /dev/null "http://127.0.0.1:8200/v1/sys/seal-status" && break
  sleep 1
done

export BAO_ADDR='http://127.0.0.1:8200'
echo
echo "--- before init ---"
bao status 2>/dev/null | grep -E 'Seal Type|Recovery Seal Type|Initialized|Sealed' | sed 's/^/   /' || true

echo
echo "--- init with recovery shares ---"
bao operator init -recovery-shares=3 -recovery-threshold=2 -format=json > /tmp/awskms-init.json
python3 - <<'PY'
import json
d = json.load(open('/tmp/awskms-init.json'))
print('   recovery keys returned:', len(d.get('recovery_keys_b64') or []))
print('   unseal  keys returned:', len(d.get('unseal_keys_b64') or []), ' <- none, KMS holds the wrapping key')
PY

sleep 5
echo
echo "--- and it unsealed itself ---"
bao status | grep -E 'Seal Type|Sealed|Total Recovery Shares' | sed 's/^/   /'

cat <<'NOTE'

   The root key was wrapped by a KMS key that OpenBao cannot read, only use.
   Against real AWS the only change is deleting the `endpoint` line.

   /tmp/awskms-init.json holds the recovery keys.
NOTE
