global:
  tlsDisable: true
server:
  image: { repository: openbao/openbao, tag: "2.6.1" }
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address     = "[::]:8200"
        tls_disable = 1
      }
      storage "file" { path = "/openbao/data" }
  dataStorage: { enabled: true, size: 1Gi }
  readinessProbe: { enabled: true }
  livenessProbe: { enabled: false }
injector: { enabled: false }
