#!/usr/bin/env bash
#
# Builds an OpenBao instance that unseals itself from a PKCS#11 token, using
# SoftHSM as the token and the external kms-pkcs11 plugin as the seal.
#
# The interesting part is the ordering. The token is provisioned when the
# container starts, the same way a real HSM partition exists before you arrive.
# The KEY is generated by this script, explicitly, BEFORE `bao operator init`,
# because OpenBao will not create PKCS#11 key material for you and initialising
# without it destroys the instance. See the README.
#
# Usage: ./setup-pkcs11-unseal.sh   (needs docker, kubectl, helm 3.x, k3d, the lesson 1.2 cluster)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NS=openbao-pkcs11
CLUSTER="${K3D_CLUSTER:-openbao-dev}"
IMAGE=openbao-pkcs11:lab
PIN="${BAO_HSM_PIN:-1234}"
TOKEN_LABEL=openbao
KEY_LABEL=bao-unseal

echo "==> 1. Build the lab image and import it into k3d"
# One image, because PKCS#11 is a library call rather than a network protocol:
# OpenBao, libsofthsm2.so and the plugin all have to be in the same container.
docker build -q -t "$IMAGE" "$HERE" >/dev/null
k3d image import "$IMAGE" -c "$CLUSTER" >/dev/null 2>&1
echo "   $IMAGE imported into k3d cluster $CLUSTER"

echo "==> 2. Render the plugin name and checksum into the values"
# Both are architecture-specific, and the sha256sum has to be the hash of the
# binary that is actually in the image. Reading it back out of the image is the
# only way to be sure those two agree.
PLUGIN_BINARY="$(docker run --rm --entrypoint sh "$IMAGE" -c 'ls /openbao/plugins | grep ^openbao-plugin-kms-pkcs11')"
PLUGIN_SHA256="$(docker run --rm --entrypoint sh "$IMAGE" -c 'cut -d" " -f1 /openbao/plugins/.sha256')"
echo "   plugin:   $PLUGIN_BINARY"
echo "   sha256:   $PLUGIN_SHA256"

RENDERED="$(mktemp)"
trap 'rm -f "$RENDERED"' EXIT
sed -e "s|PLUGIN_BINARY|${PLUGIN_BINARY}|" \
    -e "s|PLUGIN_SHA256|${PLUGIN_SHA256}|" \
    "$HERE/values-pkcs11.yaml" > "$RENDERED"

echo "==> 3. Install, with the PIN in a Secret rather than the config"
helm repo add openbao https://openbao.github.io/openbao-helm >/dev/null 2>&1 || true
helm repo update >/dev/null 2>&1 || true
kubectl create namespace "$NS" >/dev/null 2>&1 || true
kubectl -n "$NS" delete secret softhsm-pin >/dev/null 2>&1 || true
kubectl -n "$NS" create secret generic softhsm-pin --from-literal=pin="$PIN" >/dev/null
helm install openbao openbao/openbao -n "$NS" --version 0.29.2 --values "$RENDERED" >/dev/null

# Running, not Ready. The chart's readiness probe is `bao status`, which exits
# non-zero until the instance is initialised, and it cannot be initialised
# until the key below exists. The pod therefore stays un-Ready for this whole
# section, the Service has no endpoints, and port-forwarding to the service
# would hang. Forward to the pod by name instead.
echo "==> 4. Wait for the pod to be Running (it will not be Ready yet)"
for _ in $(seq 60); do
  phase="$(kubectl -n "$NS" get pod/openbao-0 -o jsonpath='{.status.phase}' 2>/dev/null || true)"
  [ "$phase" = "Running" ] && break
  sleep 3
done
[ "$phase" = "Running" ] || { echo "pod never reached Running (phase: ${phase:-absent})" >&2; exit 1; }
kubectl -n "$NS" logs openbao-0 | grep -E 'hsm-entrypoint|Auto Seal' | sed 's/^/   /' || true

echo
echo "==> 5. Generate the AES-256 key, BEFORE init"
# This is the step the whole lesson is about. OpenBao does not create PKCS#11
# key material. Initialise without it and the barrier is written, the init call
# fails while storing the root key, and you are left with an instance that
# reports Initialized=true, holds no recovery keys, and cannot be recovered.
if kubectl -n "$NS" exec openbao-0 -- pkcs11-tool \
      --module /usr/lib/softhsm/libsofthsm2.so --token-label "$TOKEN_LABEL" \
      --login --pin "$PIN" --list-objects 2>/dev/null | grep -q "label:.*${KEY_LABEL}"; then
  echo "   key '$KEY_LABEL' already exists"
else
  kubectl -n "$NS" exec openbao-0 -- pkcs11-tool \
    --module /usr/lib/softhsm/libsofthsm2.so --token-label "$TOKEN_LABEL" \
    --login --pin "$PIN" --keygen --key-type AES:32 --label "$KEY_LABEL" --id 01 \
    | sed 's/^/   /'
fi

echo
echo "==> 6. Restart so the seal picks up the key, then initialise"
# The seal is configured once, at startup, and it resolved key_label before the
# key existed. A restart is the cheapest way to make it look again.
kubectl -n "$NS" delete pod openbao-0 >/dev/null
sleep 5
for _ in $(seq 60); do
  phase="$(kubectl -n "$NS" get pod/openbao-0 -o jsonpath='{.status.phase}' 2>/dev/null || true)"
  [ "$phase" = "Running" ] && break
  sleep 3
done

# Port-forward to the POD, not the service: the service has no endpoints while
# the pod is un-Ready.
kubectl -n "$NS" port-forward pod/openbao-0 8200:8200 >/tmp/pf-pkcs11.log 2>&1 &
for _ in $(seq 30); do
  curl -s --max-time 2 -o /dev/null "http://127.0.0.1:8200/v1/sys/seal-status" && break
  sleep 1
done

export BAO_ADDR='http://127.0.0.1:8200'
echo
echo "--- before init ---"
bao status 2>/dev/null | grep -E 'Seal Type|Recovery Seal Type|Initialized|Sealed' | sed 's/^/   /' || true

echo
echo "--- init with recovery shares ---"
bao operator init -recovery-shares=3 -recovery-threshold=2 -format=json > /tmp/pkcs11-init.json
python3 - <<'PY'
import json
d = json.load(open('/tmp/pkcs11-init.json'))
print('   recovery keys returned:', len(d.get('recovery_keys_b64') or []))
print('   unseal  keys returned:', len(d.get('unseal_keys_b64') or []), ' <- none, the token holds the key')
PY

sleep 5
echo
echo "--- and it unsealed itself ---"
bao status | grep -E 'Seal Type|Sealed|Total Recovery Shares' | sed 's/^/   /'

cat <<'NOTE'

   The AES key never left the token. OpenBao asked the PKCS#11 library to
   unwrap the root key and the library did it in process.

   /tmp/pkcs11-init.json holds the recovery keys. They authorise privileged
   operations against a running instance; they are not an unseal path, and
   they cannot rebuild the token if you lose the volume.
NOTE
